### ISSUE TITLE
я скачал проект, запустил тест, он упал. надо сделать так чтоб не падал, т.е например в @Before добавить создание файла, если его нет

### ISSUE THREAD

**Issue by javaPoweredHero** [RAVIL93/UnigueIPParser#14]
https://github.com/RAVIL93/UnigueIPParser/blob/cbcdba5f0b5b4086370f4f6599dc165ef80ab2f4/src/test/java/ru/redplanet/ipparser/UniqIpParserTest.java#L10

**Comment by RAVIL93** [comment]
добавил
