### ISSUE TITLE
я бы добавил пояснение тут к каждому шагу, а то с ходу не разобраться

### ISSUE THREAD

**Issue by javaPoweredHero** [RAVIL93/UnigueIPParser#15]
https://github.com/RAVIL93/UnigueIPParser/blob/cbcdba5f0b5b4086370f4f6599dc165ef80ab2f4/src/main/java/ru/redplanet/ipparser/UniqIpParser.java#L18

**Comment by RAVIL93** [comment]
добавил , но предполагаю коментарии нужны в стилистики javadoc ?
