### ISSUE TITLE
а зачем тут queue если у тебя там linked list ? И вообще linked list бесполезная структура, всегда нужно использовать array list, тк он быстрее для всех операций

### ISSUE THREAD

**Issue by javaPoweredHero** [RAVIL93/UnigueIPParser#16]
https://github.com/RAVIL93/UnigueIPParser/blob/cbcdba5f0b5b4086370f4f6599dc165ef80ab2f4/src/main/java/ru/redplanet/ipparser/RandomIpWriter.java#L16

**Comment by RAVIL93** [comment]
норм все
