### ISSUE TITLE
форматирование сьехало, нажимай везде ctrl alt l + добавь коммент в метод main что надо запускать тест и ок

### ISSUE THREAD

**Issue by javaPoweredHero** [RAVIL93/UnigueIPParser#17]
https://github.com/RAVIL93/UnigueIPParser/blob/55c0ee40d2950b6ff1ad891a520597bd3dd1cdd4/src/test/java/ru/redplanet/ipparser/UniqIpParserTest.java#L16

**Comment by RAVIL93** [comment]
странно почему у тебя форматирование показывает , кругом прожимал  ctrl alt l   поменялось только в 1 файле и то один пробел .
